import keras
from . import backend

def generate_decoder(model):
    """
    This function attempts to extend a provided model, using a simple algorithm
    which uses the ordering of the layers leading up to the specified representation
    layer to generate a decoder branch that reconstructs the model input.

    The algorithm for generating the structure of the decoder is as follows:

    - Divide the structure layers of the model leading up to the representation layer
      into blocks, where each trainable layer indicates the first layer in a new block
    - Reverse the order of the blocks, while maintaining the order of the layers within
      each block (i.e. [[A, B, C], [D, E, F]] goes to  [[D, E, F], [A, B, C]])
    - Remove all non-trainable layers from the last block of the decoder. This helps to
      ensure that the input data can be reconstructed without loss of generality due to
      the range of activation functions.

    Additional methods are employed to help ensure consistent change of shape between
    each layer of the decoder, resulting in a final output shape that is the same
    as the input shape of the model (ex. Conv2D layers are converted to Conv2DTranspose layers,
    and vice versa).

    For this function to work well, the provided model should be a linear, and the
    specified representation layer should be a Keras Flatten layer. This function does not work if the
    layers prior to the specified representation layer for a model contain branching or merging. Additionally,
    the representation layer should be relatively deep in the model, though it does not necessarily have to be
    at the end of the model. If you model already contains a Flatten layer (ex. 2D image data is flattened
    to a 1D vector), it is likely best to specify that layer as the representation layer.

    Args:
        model: An instance of :code:`imbal.classification.Model` or :code:`imbal.regression.Model`

    Returns:
        A tuple of the form :code:`(model, layers)`, where :code:`model` is the decoder-extended
        model, and :code:`layers` is a list of layer generated by this function.
    """

    representation_layer_index = backend.tools.positive_model_layer_index(model, model._representation_layer_index)
    reverse_model = model.layers[:representation_layer_index][::-1]

    def _detect_branches(layers):
        for layer in layers:
            if len(layer._outbound_nodes) > 1:
                return True
            if len(layer._inbound_nodes) > 1:
                return True
        return False

    if _detect_branches(reverse_model):
        raise RuntimeError("In order to generate a decoder branch automatically, the layers"
                           "before the specified representation layer must not contain branching"
                           "or merging paths.")

    # Determine AE blocks
    ae_blocks = []
    last_block_end_index = 0
    for index, layer in enumerate(reverse_model):
        if hasattr(layer, 'kernel_initializer') and hasattr(layer, 'bias_initializer'):
            ae_blocks.append(reverse_model[last_block_end_index:index + 1][::-1])
            last_block_end_index = index + 1
    # Exclude input layer
    if last_block_end_index != len(reverse_model) - 1:
        ae_blocks.append(reverse_model[last_block_end_index:-1][::-1])

    print('\n----- FOUND BLOCKS -----\n')  # Debug, delete later
    for block in ae_blocks:
        print('----- BLOCK -----')
        for layer in block:
            print(f'\t{layer}, {layer.get_config()}')  # Debug, delete later
    print('\n\n')

    # Perform per-layer conversions (i.e. Conv2D to Conv2DTranspose)
    # within each block
    ae_branch_blocks = []
    for block_index, block in enumerate(ae_blocks):
        current_input_shape = block[-1].output.shape[1:]
        current_ae_block = []
        reshape_layer = keras.layers.Reshape(current_input_shape,
                                             name=f'imbal_auto_generated_ae_safeguard_reshape_block_{block_index}')
        current_ae_block.append(reshape_layer)
        print('----- BLOCK -----')  # Debug, delete later
        for layer_index, layer in enumerate(block):
            new_layer = None
            config = layer.get_config()
            config['name'] = f'imbal_auto_generated_ae_block_{block_index}_layer_{layer_index}'
            if isinstance(layer, keras.layers.Conv2D):
                layer_shape_change = layer.input.shape[-1] / layer.output.shape[-1]
                config.pop('groups', None)
                config['filters'] = round(config['filters'] * layer_shape_change)
                new_layer = keras.layers.Conv2DTranspose(**config)
            elif isinstance(layer, keras.layers.Conv2DTranspose):
                layer_shape_change = layer.input.shape[-1] / layer.output.shape[-1]
                config['filters'] = round(config['filters'] * layer_shape_change)
                new_layer = keras.layers.Conv2D(**config)
            elif isinstance(layer, keras.layers.MaxPooling2D):
                config.pop('groups', None)
                config['strides'] = layer.strides
                config.pop('pool_size', None)
                config['kernel_size'] = layer.pool_size
                config['filters'] = round(block[layer_index - 1].get_config()['filters'])
                new_layer = keras.layers.Conv2DTranspose(**config)
            elif isinstance(layer, keras.layers.Dense):
                units = layer.input.shape[-1]
                config['units'] = units
                new_layer = keras.layers.Dense(**config)
            elif isinstance(layer, keras.layers.Flatten):
                config.pop('data_format', None)
                config.pop('channels_last', None)
                config['target_shape'] = block[layer_index - 1].output.shape[1:]
                new_layer = keras.layers.Reshape(**config)

            # Failsafe for non-trainable layers
            elif not (hasattr(layer, 'kernel_initializer') and hasattr(layer, 'bias_initializer')):
                new_layer = type(layer).from_config(config)

            # Raise exception if layer could not be converted
            if new_layer is None:
                raise RuntimeError(f'Unable to perform AE conversion of layer {layer}')

            print(f'\t{new_layer}')  # Debug, delete later
            print(f'\t\t{new_layer.get_config()}')  # Debug, delete later

            current_ae_block.append(new_layer)
        ae_branch_blocks.append(current_ae_block)

    for block in ae_branch_blocks:
        for i in range(1, len(block)):
            current_layer = block[i]
            if isinstance(current_layer, keras.layers.Reshape):
                prev_layer = block[i - 1]
                block[i - 1] = current_layer
                block[i] = prev_layer

    # For better results, last block should only be made on trainable layers (activation
    # and normalization layers can sometimes prevent reaching the goal reconstruction)
    refined_last_block = []
    for layer in ae_branch_blocks[-1]:
        if hasattr(layer, 'kernel_initializer') and hasattr(layer, 'bias_initializer') \
                or isinstance(layer, keras.layers.MaxPooling2D) or isinstance(layer, keras.layers.Reshape):
            refined_last_block.append(layer)
    ae_branch_blocks[-1] = refined_last_block

    print('\n----- AE CONVERSION -----\n')  # Debug, delete later
    for block in ae_branch_blocks:
        print('----- BLOCK -----')
        for layer in block:
            print(f'\t{layer}, {layer.get_config()}')  # Debug, delete later

    # Connect final layer structure
    ae_layer_list = [layer for block in ae_branch_blocks for layer in block]
    last_layer = model.layers[representation_layer_index]
    for layer in ae_layer_list:
        print(layer.name)
        print(last_layer.output.shape)
        layer(last_layer.output)
        last_layer = layer

    if not (hasattr(model, 'inputs') and hasattr(model, 'outputs')):
        raise RuntimeError('Model\'s "inputs" and "outputs" fields are not set.')

    model._extended_model = model.__class__(inputs=model.inputs, outputs=model.outputs + [ae_layer_list[-1].output])
    model._decoder_branch = ae_layer_list