from imbal.util.backend.stratified_sampling.split import split as util_split
from imbal.util.backend.constants import ModelType

def split(
    x_set,
    y_set,
    sample_weights=None,
    test_size=None,
    train_size=None,
    seed=None,
    shuffle=True
) -> tuple:
    """
    Args:
        x_set: A NumPy array of data points, arranged as a column vector
        y_set: A NumPy array of labels, arranged as a column vector
        sample_weights: Optional, default :code:`None`. A NumPy array of weights,
            arranged as a column vector.
        test_size: Optional, default :code:`None`. The percentage of data that
            should be contained in the test split.
        train_size: Optional, default :code:`None`. The percentage of data that
            should be contained in the train split. If specified, overrides the
            value of :code:`test_size`.
        seed: Optional, default :code:`None`. The random seed to use for shuffling.
            When set to :code:`None`, a seed is generated by the system.
        shuffle: Optional, default :code:`True`. Whether to shuffle the data before splitting.

    Returns:
        Two SimpleDataset objects in a tuple of the form :code:`(train_dataset, test_dataset)`.

    In the case of regression, there are no explict classes to stratify data on. Instead,
    the data is sorted based on its label, then seperated into pseudo classes, which are then split based on
    the specified split percentage. These psuedo-classes are of size 10 or 100 based on the
    specified split percentage, therefore it is encouraged that the split percentage is a
    multiple of 10% for smaller data sets, and a multiple of 1% for larger data sets.

    Example:

     .. code-block:: python

        >>> data = np.arange(21).reshape(-1,1)
        >>> labels = np.arange(21).reshape(-1,1)
        >>> weights = (np.ones(21) / 21).reshape(-1, 1)

        >>> train_set, test_set = split(data, labels, weights, test_size=0.20)
        # SimpleDataset.get_unzipped returns data, labels, and weights separately
        >>> x_train, y_train, w_train = train_set.get_unzipped()
        >>> x_test, y_test, w_test = test_set.get_unzipped()

        >>> print(y_train)
        [20. 16.  8.  2. 14.  1. 11.  9. 19.  0.  5. 13. 15.  6. 17. 12.  7.]
        >>> print(y_test)
        [10.  3.  4. 18.]

    """
    return util_split(
        x_set,
        y_set,
        sample_weights=sample_weights,
        test_size=test_size,
        train_size=train_size,
        seed=seed,
        shuffle=shuffle,
        mode=ModelType.REGRESSION
    )