from imbal.util.backend.stratified_sampling.split import split as util_split
from imbal.util.backend.constants import ModelType

def split(
        x_set,
        y_set,
        sample_weights=None,
        test_size=0.2,
        train_size=None,
        seed=None,
        shuffle=True
    ) -> tuple:
    """
        Performs a stratified split, creating two subsets of the provided data that
        is as close to the specified split percentage as possible, while maintaining that
        the data distribution within the subsets is as close to the original distribution
        of the data as possible.

        Args:
            x_set: A NumPy array of data points, arranged as a column vector
            y_set: A NumPy array of labels, arranged as a column vector
            sample_weights: Optional, default :code:`None`. A NumPy array of weights,
                arranged as a column vector.
            test_size: Optional, default :code:`0.2`. The percentage of data that
                should be contained in the test split.
            train_size: Optional, default :code:`None`. The percentage of data that
                should be contained in the train split. If specified, overrides the
                value of :code:`test_size`.
            seed: Optional, default :code:`None`. The random seed to use for shuffling.
                When set to :code:`None`, a seed is generated by the system.
            shuffle: Optional, default :code:`True`. Whether to shuffle the data before splitting.

        Returns:
            Two tuples, which are both length 3 if :code:`sample_weights` is specified, otherwise length 2.

        Example:

         .. code-block:: python

            >>> import imbal
            >>> import numpy as np

            >>> data = np.arange(21).reshape(-1,1)
            >>> labels = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]).reshape(-1,1)
            >>> weights = (np.ones(21) / 21).reshape(-1, 1)

            >>> train_set, test_set = imbal.classification.split(data, labels, weights, test_size=0.20)
            # SimpleDataset.get_unzipped returns data, labels, and weights separately
            >>> x_train, y_train, w_train = train_set.get_unzipped()
            >>> x_test, y_test, w_test = test_set.get_unzipped()

            >>> print(y_train)
            [[0] [0] [1] [0] [0] [0] [0] [0] [0] [1] [0] [1] [0] [1] [0] [1]]
            >>> print(y_test)
            [[0] [1] [0] [0] [0]]

        """

    return util_split(
        x_set,
        y_set,
        sample_weights=sample_weights,
        test_size=test_size,
        train_size=train_size,
        seed=seed,
        shuffle=shuffle,
        mode=ModelType.CLASSIFICATION
    )